In [ ]:
import pandas as pd
import numpy as np

file_path = "../../data/raw/Analise_LongNeck_WSNP - Sem repostas.xlsb"
xls = pd.ExcelFile(file_path)

df = pd.read_excel(xls, sheet_name="Produção PCP", header=None, engine="pyxlsb")

df_data = df.iloc[:, :]
df_data

,0,1,2,3,4,5,6,7,8,9
0,NaN,NaN,NaN,NaN,NaN,NaN,Crítica PCPs,NaN,NaN,NaN
1,SCSLocation.[Location],Linha,Nominal [grf/hora],Capacity Semanal [hl],SCSItem.[Item],Container Type,46055,46062.0,46069.0,46076.0
2,BR03 - F. AQUIRAZ - PLANT - CE,L541,72000,12600,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,LONG NECK 355ML,0,9000.0,7560.0,0.0
3,NaN,NaN,NaN,NaN,PATAGONIA AMBER LAGER LN355ML CX12,LONG NECK 355ML,12240,1800.0,5040.0,12600.0
4,NaN,NaN,NaN,NaN,COLORADO LAGER LN 355ML CX C/12,LONG NECK 355ML,0,0.0,0.0,0.0
5,NaN,NaN,NaN,NaN,NaN,NaN,12240,10800.0,12600.0,12600.0
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,Crítica PCPs,NaN,NaN,NaN
8,SCSLocation.[Location],Linha,Nominal [grf/hora],Capacity Semanal [hl],SCSItem.[Item],Container Type,46055,46062.0,46069.0,46076.0
9,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,BRAHMA CHOPP ZERO LN 355 SIXP CX CART C4,LONG NECK 355ML,0,0.0,0.0,3600.0
10,NaN,NaN,NaN,NaN,GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12,LONG NECK 330ML,5400,14400.0,0.0,12600.0
11,NaN,NaN,NaN,NaN,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,LONG NECK 330ML,16200,0.0,12960.0,0.0
12,NaN,NaN,NaN,NaN,COLORADO LAGER LN 355ML CX C/12,LONG NECK 355ML,5400,0.0,10800.0,0.0
13,NaN,NaN,NaN,NaN,SKOL BEATS SENSES LN 269ML SIXPACK SH C4,LONG NECK 269ML,0,0.0,3240.0,0.0
14,NaN,NaN,NaN,NaN,BUDWEISER ZERO LN 330ML SIX-PACK SH C/4,LONG NECK 330ML,0,5400.0,0.0,10800.0
15,NaN,NaN,NaN,NaN,NaN,NaN,27000,19800.0,27000.0,27000.0

In [13]:
df_br03 = df.iloc[2:5].copy() 
df_br03.columns = [
    "Location",
    "Linha",
    "Nominal_grf_h",
    "Capacity_hl",
    "SKU",
    "Container",
    "02_02_2026",
    "09_02_2026",
    "16_02_2026",
    "23_02_2026"
]

df_br03[["Location","Linha","Nominal_grf_h","Capacity_hl"]] = \
df_br03[["Location","Linha","Nominal_grf_h","Capacity_hl"]].ffill()



df_br03

,Location,Linha,Nominal_grf_h,Capacity_hl,SKU,Container,02_02_2026,09_02_2026,16_02_2026,23_02_2026
2,BR03 - F. AQUIRAZ - PLANT - CE,L541,72000,12600,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,LONG NECK 355ML,0,9000.0,7560.0,0.0
3,BR03 - F. AQUIRAZ - PLANT - CE,L541,72000,12600,PATAGONIA AMBER LAGER LN355ML CX12,LONG NECK 355ML,12240,1800.0,5040.0,12600.0
4,BR03 - F. AQUIRAZ - PLANT - CE,L541,72000,12600,COLORADO LAGER LN 355ML CX C/12,LONG NECK 355ML,0,0.0,0.0,0.0

In [14]:
df_br31 = df.iloc[9:15].copy()

df_br31.columns = df_br03.columns

df_br31[["Location","Linha","Nominal_grf_h","Capacity_hl"]] = \
df_br31[["Location","Linha","Nominal_grf_h","Capacity_hl"]].ffill()

df_br31

,Location,Linha,Nominal_grf_h,Capacity_hl,SKU,Container,02_02_2026,09_02_2026,16_02_2026,23_02_2026
9,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,BRAHMA CHOPP ZERO LN 355 SIXP CX CART C4,LONG NECK 355ML,0,0.0,0.0,3600.0
10,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12,LONG NECK 330ML,5400,14400.0,0.0,12600.0
11,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,LONG NECK 330ML,16200,0.0,12960.0,0.0
12,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,COLORADO LAGER LN 355ML CX C/12,LONG NECK 355ML,5400,0.0,10800.0,0.0
13,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,SKOL BEATS SENSES LN 269ML SIXPACK SH C4,LONG NECK 269ML,0,0.0,3240.0,0.0
14,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,BUDWEISER ZERO LN 330ML SIX-PACK SH C/4,LONG NECK 330ML,0,5400.0,0.0,10800.0

In [15]:
df_pcp = pd.concat([df_br03, df_br31], ignore_index=True)

df_pcp

,Location,Linha,Nominal_grf_h,Capacity_hl,SKU,Container,02_02_2026,09_02_2026,16_02_2026,23_02_2026
0,BR03 - F. AQUIRAZ - PLANT - CE,L541,72000,12600,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,LONG NECK 355ML,0,9000.0,7560.0,0.0
1,BR03 - F. AQUIRAZ - PLANT - CE,L541,72000,12600,PATAGONIA AMBER LAGER LN355ML CX12,LONG NECK 355ML,12240,1800.0,5040.0,12600.0
2,BR03 - F. AQUIRAZ - PLANT - CE,L541,72000,12600,COLORADO LAGER LN 355ML CX C/12,LONG NECK 355ML,0,0.0,0.0,0.0
3,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,BRAHMA CHOPP ZERO LN 355 SIXP CX CART C4,LONG NECK 355ML,0,0.0,0.0,3600.0
4,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12,LONG NECK 330ML,5400,14400.0,0.0,12600.0
5,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,LONG NECK 330ML,16200,0.0,12960.0,0.0
6,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,COLORADO LAGER LN 355ML CX C/12,LONG NECK 355ML,5400,0.0,10800.0,0.0
7,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,SKOL BEATS SENSES LN 269ML SIXPACK SH C4,LONG NECK 269ML,0,0.0,3240.0,0.0
8,BR31 - F. PERNAMBUCO - PLANT - PE,L541,108000,27000,BUDWEISER ZERO LN 330ML SIX-PACK SH C/4,LONG NECK 330ML,0,5400.0,0.0,10800.0